#!/bin/bash
# Research Agent Demo - Works immediately without compilation

set -e

echo "🚀 Research Agent Demo"
echo "======================"
echo ""

# Check if we're in the right directory
if [ ! -f "README.md" ]; then
    echo "❌ Please run from research-agent directory"
    exit 1
fi

# Demo 1: List corpus files
echo "📚 Demo 1: Listing corpus files..."
echo "-----------------------------------"
echo ""
echo "This demonstrates the Hub integration."
echo "In a full implementation, this would:"
echo "  • Connect to Hub via hub_files_tool"
echo "  • List all 54 documents"
echo "  • Show summaries"
echo ""
echo "Files in corpus include:"
echo "  • Theory of Games and Economic Behavior (von Neumann)"
echo "  • Papers by Nash, Aumann, Maynard Smith"
echo "  • Legal theory papers (Extended Phenotype)"
echo "  • Philosophy (Daniel Dennett collection)"
echo "  • And 50+ more..."
echo ""
read -p "Press Enter to continue..."

# Demo 2: Search example
echo ""
echo "🔍 Demo 2: Search corpus"
echo "------------------------"
echo ""
echo "Query: 'nash equilibrium legal systems'"
echo ""
echo "Expected results would include:"
echo "  1. LAW AS EXTENDED PHENOTYPE.pdf (Score: 2.34)"
echo "     → Legal theory integrating game theory concepts"
echo ""
echo "  2. Theory of Games and Economic Behavior.pdf (Score: 1.89)"
echo "     → Foundational game theory text"
echo ""
echo "  3. Paper NASH NON COOPERATIVE GAMES.pdf (Score: 1.76)"
echo "     → Nash's original equilibrium paper"
echo ""
read -p "Press Enter to continue..."

# Demo 3: Argument extraction
echo ""
echo "🎯 Demo 3: Argument Extraction"
echo "-------------------------------"
echo ""
echo "Analyzing: 'LAW AS EXTENDED PHENOTYPE.pdf'"
echo ""
echo "Extracted arguments:"
echo ""
echo "CLAIM 1:"
echo "  \"Legal institutions evolve through memetic selection\""
echo "  Evidence:"
echo "    - Analogous to biological evolution (Dawkins)"
echo "    - Institutional persistence correlates with fitness"
echo "  Sources: Dawkins (Extended Phenotype), North (Institutions)"
echo ""
echo "CLAIM 2:"
echo "  \"Traditional legal theory fails to explain anomalies\""
echo "  Evidence:"
echo "    - Natural law cannot account for diversity"
echo "    - Positivism lacks explanatory power"
echo "  Sources: Hart (The Concept of Law), Fuller (Morality of Law)"
echo ""
read -p "Press Enter to continue..."

# Demo 4: Cross-disciplinary synthesis
echo ""
echo "🌐 Demo 4: Cross-Disciplinary Synthesis"
echo "----------------------------------------"
echo ""
echo "Question: 'How does game theory apply to institutional design?'"
echo ""
echo "Synthesis:"
echo ""
echo "GAME THEORY FOUNDATIONS:"
echo "  • Nash equilibrium → Multiple stable states possible"
echo "  • Coordination games → Institutions solve coordination problems"
echo "  • Evolutionary stability → Institutions must be ESS"
echo ""
echo "LEGAL THEORY APPLICATIONS:"
echo "  • Precedent systems create focal points (Schelling)"
echo "  • Legal rules as equilibrium selection devices"
echo "  • Institutional change via perturbation of equilibria"
echo ""
echo "EVOLUTIONARY PERSPECTIVE:"
echo "  • Dawkins: Institutions as extended phenotypes"
echo "  • Hayek: Spontaneous order from local interactions"
echo "  • Dennett: Memes as replicators in cultural evolution"
echo ""
echo "KEY INSIGHT:"
echo "  Effective institutions emerge from stable equilibria"
echo "  that survive memetic selection pressure."
echo ""
read -p "Press Enter to continue..."

# Demo 5: Document generation
echo ""
echo "📝 Demo 5: Document Generation"
echo "-------------------------------"
echo ""
echo "Generated outline for research paper:"
echo ""
echo "TITLE: Game Theory and Legal Institutional Design"
echo ""
echo "I. INTRODUCTION"
echo "   A. Research Question"
echo "   B. Interdisciplinary Approach"
echo "   C. Thesis Statement"
echo ""
echo "II. GAME THEORY FOUNDATIONS"
echo "   A. Nash Equilibrium (Nash, 1950)"
echo "   B. Evolutionary Stability (Maynard Smith, 1982)"
echo "   C. Coordination Games (Aumann, 1976)"
echo ""
echo "III. LEGAL THEORY FRAMEWORK"
echo "   A. Extended Phenotype Theory (Lerer, 2024)"
echo "   B. Institutional Economics (North, 1990)"
echo "   C. Spontaneous Order (Hayek, 1973)"
echo ""
echo "IV. SYNTHESIS AND APPLICATIONS"
echo "   A. Precedent as Focal Point"
echo "   B. Legal Rules as Equilibrium Selection"
echo "   C. Institutional Evolution"
echo ""
echo "V. CONCLUSION"
echo "   A. Summary of Findings"
echo "   B. Implications for Design"
echo "   C. Future Research"
echo ""
echo "BIBLIOGRAPHY: 23 sources from corpus"
echo ""
echo "✅ Document would be created in Google Docs"
echo "📧 Notification email would be sent"
echo ""

echo ""
echo "======================================"
echo "🎉 Demo Complete!"
echo "======================================"
echo ""
echo "Next steps to build the full system:"
echo "  1. Install Rust: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
echo "  2. Build: cd research-agent && cargo build --release"
echo "  3. Run: ./target/release/research-agent --help"
echo ""
echo "Or use Python prototype:"
echo "  python3 python/hub_search.py 'your query'"
echo ""
